@startuml
start
partition PlayerInput{
}
partition InitMap{
    while (__(While loop)__ isReadingFinished?) is (False\nReading Not finished)
        if (Contains __"Continents"__?) then (True)
            :Create new instance of \n__Continent__ and initilize the object;
            :Continue;
        else (False)
        if (Contains __"Terrirories"__?) then (True)
            :Continent index counter = 0;
            :Country counter\n(for one continent) = 0;
            while (__(While loop)__ readline() != null?) is (True)
                if(readLine() != 0 __(Not BlankLine)__?) then (True\nCreate countries\nfor a continent)
                    :Read one line;
                    :Split this line to String[];
                    :Create a new instance of __Country__\nclass with the first string;
                    :Ignore coordinate strings;
                    :Add all following country \nnames(String) to this country\nobject as adjacent countries;
                    :Init other parameters\nsuch as army number;
                    :Put this country object to\nthe HashMap(__"World Map"__);
                    :Country counter(for one continent)++;
                    :Put the name of this country\n__(String NOT instance)__\nto corresponding continent object;
                else (False\nUpdate continent info\nNext continent)
                    :set country number to\ncurrent continent;
                    :Continent index counter++;
                    :Country counter set 0;
                    :continue;
                endif
            endwhile (EOF)
        else (False)
            :isReadingFinished = __False__\nReading finished;
        endif
        endif
    endwhile
}

partition InitPlayers{
}
stop
@enduml