@startuml

start
partition PlayerInput{

    :Input filepath;
    if (Whether input map path valid?) then (True)
         :Input path;
    else (False)
        :Default sample map;
    endif
    :Input player numbers;
    if (Whether have input valid?) then (True)
        :Input player number;
    else (False)
        :default 3 players;
    endif
    :Player click "Confirm" button;
    }

partition InitMap{
}
stop

@enduml